# Generated by Django 5.0.6 on 2025-01-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinfo',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
