# Generated by Django 5.0.6 on 2024-12-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='boards',
            field=models.ManyToManyField(null=True, related_name='board_pins', to='board.board'),
        ),
    ]
