# Generated by Django 5.0.6 on 2025-01-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('pin', '0004_alter_pin_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(default='generic', on_delete=django.db.models.deletion.DO_NOTHING, related_name='pins', to='category.category'),
        ),
    ]
