# Generated by Django 5.0.6 on 2025-01-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('pin', '0005_pin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pins', to='category.category'),
        ),
    ]
